FROM python:3.11.9-slim

WORKDIR /app

COPY requirements.txt .

# Install stress-ng to induce CPU load
RUN apt-get update && apt-get install -y stress-ng && rm -rf /var/lib/apt/lists/*
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

# Command to run the application while inducing CPU load in the background
CMD ["sh", "-c", "stress-ng --cpu 1 & uvicorn todo_v2:app --host 0.0.0.0 --port 8000"]
